export const SET_FETCHING = "SET_FETCHING";
export const SET_FETCH_SUCCESS = "SET_FETCH_SUCCESS";
export const SET_FETCH_ERROR = "SET_FETCH_ERROR";
export const SET_DATE_TIME = "SET_DATE_TIME";
export const SET_SHOWERROR = "SET_SHOWERROR";
